version: '3.3'
services:
  postgres:
    image: postgres:latest
    container_name: test-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5436:5432'
    volumes:
      - database-data:/var/lib/postgresql/data/

volumes:
  database-data:
    driver: local
